export const CREATE_USER = "CREATE_USER";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS,";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS,";
export const LOAD_CAMPAIGNS_SUCCESS = "LOAD_CAMPAIGNS_SUCCESS ";
export const BEGIN_API_CALL = "BEGING_API_CALL";
